coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

comment:
  layout: "header, diff, files, footer"
  behavior: default
  require_changes: false

ignore:
  - "bootstrap/**/*"
  - "config/**/*"
  - "public/**/*"
  - "resources/**/*"
  - "routes/**/*"
  - "storage/**/*"
  - "database/factories/**/*"
  - "database/seeders/**/*"
  - "tests/**/*"
